---
- name: 1LINK Network Change Automation
  hosts: all
  gather_facts: no

  tasks:

    - name: Create VLAN
      raw: |
        configure terminal
        vlan {{ vlan_id }}
        name {{ vlan_name }}
        end
      when: change_type == "create_vlan"

    - name: Delete VLAN
      raw: |
        configure terminal
        no vlan {{ vlan_id }}
        end
      when: change_type == "delete_vlan"

    - name: Interface Up
      raw: |
        configure terminal
        interface {{ interface_name }}
        no shutdown
        end
      when: change_type == "interface_up"

    - name: Interface Down
      raw: |
        configure terminal
        interface {{ interface_name }}
        shutdown
        end
      when: change_type == "interface_down"

    - name: Update Interface Description
      raw: |
        configure terminal
        interface {{ interface_name }}
        description {{ interface_description }}
        end
      when: change_type == "update_description"
