---
- name: 1LINK Validation Engine
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    vlan_id_str: "{{ vlan_id | string }}"

  tasks:

    # ---------------------------
    # INPUT CHECK
    # ---------------------------

    - name: Fail if VLAN ID missing
      fail:
        msg: "VLAN ID is required"
      when:
        - change_type in ["create_vlan", "delete_vlan"]
        - vlan_id is not defined

    - name: Fail if Interface missing
      fail:
        msg: "Interface name is required"
      when:
        - change_type in ["interface_up", "interface_down", "update_description"]
        - interface_name is not defined or interface_name == ""

    # ---------------------------
    # GET VLAN DATA
    # ---------------------------

    - name: Show VLAN
      cisco.ios.ios_command:
        commands:
          - show vlan brief
      register: vlan_output

    - name: Check VLAN Exists
      set_fact:
        vlan_exists: "{{ vlan_id_str in vlan_output.stdout[0] }}"

    - name: Fail if VLAN already exists
      fail:
        msg: "VLAN {{ vlan_id }} already exists"
      when:
        - change_type == "create_vlan"
        - vlan_exists

    - name: Fail if VLAN does not exist
      fail:
        msg: "VLAN {{ vlan_id }} does not exist"
      when:
        - change_type == "delete_vlan"
        - not vlan_exists

    # ---------------------------
    # INTERFACE CHECK
    # ---------------------------

    - name: Show Interface
      cisco.ios.ios_command:
        commands:
          - show running-config interface {{ interface_name }}
      register: int_output
      when: change_type in ["interface_up", "interface_down", "update_description"]

    - name: Validation Passed
      debug:
        msg: "Validation successful"
